- name: Install Docker & Docker Compose
  hosts: homelab
  become: true

  tasks:
    - name: Install required system packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes
    - name: Create dir for Docker's GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Add Docker's official GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true
    - name: Add Docker Respository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian trixie stable"
        state: present
        filename: docker
    - name: Install Docker Engine and plugins
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present 
        update_cache: yes
    - name: Add current user to Docker's group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
