- name: Storage Setup
  hosts: homelab
  become: true
  vars:
    disk_uuid: "3c0c0387-fd32-4768-91e3-6909506d57fa"
    
    mount_point: /mnt/storage

  tasks:
    - name: Mount the disk persistently
      mount:
        path: "{{ mount_point }}"
        src: "UUID={{ disk_uuid }}"
        fstype: ext4
        state: mounted

    - name: Create organized folders
      file:
        path: "{{ mount_point }}/{{ item }}"
        state: directory
        mode: '0775'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop:
        - media
        - backups
        - torrents
        - docker_data
