- name: Apply common role
  hosts: homelab
  become: true
  roles:
    - common
    - storage
    - docker
    - traefik
    - seafile
    - immich
    # - radicale
    - navidrome
    - role: getmusic
      tags:
        - getmusic
    - autorestic
